movie/urls.py
from django.urls import path

from movie import views

urlpatterns = [
    path("", views.MovieListView.as_view(), name="index"),
    path(
        "movie_detail/<int:pk>/",
        views.MovieDetailView.as_view(),
        name="movie-detail"
    ),
    path(
        "movie_detail/<int:pk>/update/",
        views.MovieUpdateView.as_view(),
        name="update-movie"
    ),
    path(
        "movie_detail/<int:pk>/delete/",
        views.MovieDeleteView.as_view(),
        name="delete-movie"
    ),
    path("create/", views.MovieCreateView.as_view(), name="create-movie"),

    path("review/<int:pk>/", views.AddReview.as_view(), name="add-review"),
]

app_name = "movie"

movie_library/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from movie import views
from movie_library import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("movie.urls", namespace="movie")),

    # Accounts
    path("accounts/login/", views.UserLoginView.as_view(), name="login"),
    path("accounts/logout/", views.user_logout_view, name="logout"),
    path(
        "accounts/register/",
        views.RegistrationView.as_view(),
        name="register"
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

movie/models.py
from datetime import date

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from movie_library import settings


class User(AbstractUser):
    def __str__(self):
        return f"{self.username}"


class Genre(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return f"{self.name}"


class Actor(models.Model):
    avatar = models.ImageField(upload_to="actors")
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    age = models.IntegerField()

    def __str__(self):
        return f"{self.first_name} - {self.last_name}"


class Movie(models.Model):
    title = models.CharField(max_length=255)
    tagline = models.CharField(max_length=100, default="")
    description = models.TextField()
    poster = models.ImageField(upload_to="poster")
    year = models.PositiveSmallIntegerField("Release date")
    country = models.CharField(max_length=64)
    genres = models.ManyToManyField(Genre, related_name="genre")
    actors = models.ManyToManyField(Actor, related_name="film_actors")
    directors = models.ManyToManyField(Actor, related_name="film_directors")
    fess_in_world = models.PositiveSmallIntegerField(
        default=0, help_text="enter the dollar amount"
    )
    budget = models.PositiveSmallIntegerField(
        default=0, help_text="enter the dollar amount"
    )
    world_premiere = models.DateField(default=date.today)

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse("movie:movie-detail", kwargs={"pk": self.id})


class Reviews(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    text = models.TextField(max_length=4000)

    def __str__(self):
        return f"{self.user} - {self.movie}"

    class Meta:
        verbose_name = "review"
        verbose_name_plural = "reviews"

movie/views.py
from django.contrib.auth import views, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from movie.form import (
    MovieSearchForm,
    LoginForm,
    RegistrationsForm,
    ReviewForm
)
from movie.models import Movie, Actor, Genre, User


class GetData:
    @staticmethod
    def get_actors():
        return Actor.objects.all()

    @staticmethod
    def get_genres():
        return Genre.objects.all()


class MovieListView(LoginRequiredMixin, GetData, generic.ListView):
    model = Movie
    queryset = Movie.objects.all()
    ordering = ["title"]
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        title = self.request.GET.get("title", "")

        context["get_genres"] = self.get_genres()
        context["get_actors"] = self.get_actors()
        context["film_title"] = title
        context["movie"] = Movie.objects.all()
        context["search_form"] = MovieSearchForm(initial={"title": title})

        return context

    def get_queryset(self):
        title = self.request.GET.get("title")
        genres = self.request.GET.get("genres")
        if title:
            return self.queryset.filter(title__icontains=title)
        if genres:
            return self.queryset.filter(genres__name=genres)
        return self.queryset


class MovieDetailView(LoginRequiredMixin, generic.DetailView, GetData):
    model = Movie


class MovieUpdateView(LoginRequiredMixin, GetData, generic.UpdateView):
    model = Movie
    fields = "__all__"

    template_name = "movie/movie_update.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        title = self.request.GET.get("title", "")

        context["get_genres"] = self.get_genres()
        context["get_actors"] = self.get_actors()

        return context


class MovieCreateView(LoginRequiredMixin, GetData, generic.CreateView):
    model = Movie
    fields = "__all__"
    success_url = reverse_lazy("movie:index")
    template_name = "movie/movie_create.html"


class MovieDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Movie
    template_name = "movie/confirm_delete.html"
    success_url = reverse_lazy("movie:index")


class UserLoginView(views.LoginView):
    form_class = LoginForm


def user_logout_view(request):
    logout(request)
    return redirect("/accounts/login/")


class RegistrationView(generic.CreateView):
    model = User
    template_name = "registration/sign_up.html"
    form_class = RegistrationsForm
    success_url = reverse_lazy("login")


class AddReview(generic.View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if request.user.is_authenticated:
            if form.is_valid():
                form.save(commit=False)
                form.movie = movie
                form.user = request.user
                form.save()
            return redirect(movie.get_absolute_url())
        return reverse_lazy("login")

templates/base.html

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>
    Movie Library
  </title>
  <link rel="icon" type="image/png" href="{% static 'img/logo.png' %}">
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />

  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="{% static 'css/material-kit.css' %}" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body {% block body %}{% endblock body %} >

  {% block header %}
    {% include 'include/sidebar.html' %}
  {% endblock header %}

  {% block content %}
  {% endblock %}

  {% block footer %}
    {% include 'include/footer.html' %}
  {% endblock %}

  {% include 'include/scripts.html' %}



</body>
</html>

templates/include/filter_form.html


<form class="dropdown col-lg-4">
    <div class="card-body">
      <div class="input-group input-group-dynamic mb-4">
          <input class="form-control drop-button" type="button" id="dropdownMenuButton1" value="--- Click to choose genre ---" data-bs-toggle="dropdown" aria-expanded="false">
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            {% for genre in get_genres %}
              <li><a class="dropdown-item" href="?genres={{ genre.name }}">{{ genre.name }}</a></li>
            {% endfor %}
          </ul>

      </div>
    </div>
</form>

templates/include/footer.html
{% load static %}

<footer class="footer pt-5 mt-5">
  <div class="container">
     <div class="col-12">
        <div class="text-center">
          <h6 class="">
            Movie Library
          </h6>
        </div>
      </div>

      <div class="col-12">
        <div class="text-center">
          <p class="text-dark my-4 text-sm font-weight-normal">
            &copy; Coded by - <a href="https://github.com/Vitalii-Khmura" target="_blank">Vitalii Khmura</a>
          </p>
          <i class="fa fa-facebook"></i>

          <ul class="d-flex flex-row ms-n3 nav">
            <li class="nav-item">
            <a class="nav-link pe-1" href="https://www.facebook.com/CreativeTim" target="_blank">
            <i class="fab fa-facebook text-lg opacity-8" aria-hidden="true"></i>
            </a>
            </li>
            <li class="nav-item">
            <a class="nav-link pe-1" href="https://twitter.com/creativetim" target="_blank">
            <i class="fab fa-twitter text-lg opacity-8" aria-hidden="true"></i>
            </a>
            </li>
            <li class="nav-item">
            <a class="nav-link pe-1" href="https://dribbble.com/creativetim" target="_blank">
            <i class="fab fa-dribbble text-lg opacity-8" aria-hidden="true"></i>
            </a>
            </li>
            <li class="nav-item">
            <a class="nav-link pe-1" href="https://github.com/creativetimofficial" target="_blank">
            <i class="fab fa-github text-lg opacity-8" aria-hidden="true"></i>
            </a>
            </li>
            <li class="nav-item">
            <a class="nav-link pe-1" href="https://www.youtube.com/channel/UCVyTG4sCw-rOvB9oHkzZD1w" target="_blank">
            <i class="fab fa-youtube text-lg opacity-8" aria-hidden="true"></i>
            </a>
            </li>
            </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/movie/movie_create.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <header>
    <div class="page-header min-vh-100" style="background-image: url({% static 'img/back.jpeg'%});" loading="lazy">
      <span class="mask bg-gradient-dark opacity-5"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-7 d-flex justify-content-center flex-column">
            <h1 class="text-white mb-4">Movie Library</h1>
            <p class="text-white opacity-8 lead pe-5 me-5">Create Movie  </p>
            <div class="buttons">
              <a href="#content" type="button" class="btn btn-white mt-4">Get Started</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>


<section>
  <div id="content" class="container py-4">
    <div class="card-body">
      <div class="row">
        <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
          <h3 class="text-center">Create Movie</h3>
          <form role="form" id="movie-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}

            <div class="form-group">
                <label for="id_title">Title</label>
                <input type="text" class="form-control border" id="id_title" name="title">
            </div>

            <div class="form-group">
                <label for="id_tagline">Tagline</label>
                <input type="text" class="form-control border" id="id_tagline" name="tagline">
            </div>

            <div class="form-group">
                <label for="id_description">Description</label>
                <textarea class="form-control border" id="id_description" name="description" rows="4"></textarea>
            </div>

            <div class="form-group mt-3">
                <label for="id_poster">Poster</label>
                <input type="file" class="form-control-file border" id="id_poster" name="poster" accept="image/*" required>
            </div>

            <div class="form-group">
                <label for="id_year">Release Year</label>
                <input type="number" class="form-control border" id="id_year" name="year">
            </div>

            <div class="form-group">
                <label for="id_country">Country</label>
                <input type="text" class="form-control border" id="id_country" name="country">
            </div>

            <div class="form-group">
                <label for="id_genres">Genres</label>
                <select multiple class="form-control border" id="id_genres" name="genres">
                    {% for genre in form.genres.field.choices %}
                        <option value="{{ genre.0 }}">{{ genre.1 }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label for="id_actors">Actors</label>
                <select multiple class="form-control border" id="id_actors" name="actors">
                    {% for actor in form.actors.field.choices %}
                        <option value="{{ actor.0 }}">{{ actor.1 }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label for="id_directors">Directors</label>
                <select multiple class="form-control border" id="id_directors" name="directors">
                    {% for director in form.directors.field.choices %}
                        <option value="{{ director.0 }}">{{ director.1 }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label for="id_fess_in_world">Fees in World</label>
                <input type="number" class="form-control border" id="id_fess_in_world" name="fess_in_world">
            </div>

            <div class="form-group">
                <label for="id_budget">Budget</label>
                <input type="number" class="form-control border" id="id_budget" name="budget">
            </div>

            <div class="form-group">
                <label for="id_world_premiere">World Premiere</label>
                <input type="date" class="form-control border" id="id_world_premiere" name="world_premiere">
            </div>

            <div class="row">

                <div class="col-md-12 mt-3">
                  <button type="submit" class="btn bg-gradient-dark w-100">Create Movie</button>
                </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block footer %}
  {% include "include/footer.html"%}
{% endblock %}

templates/movie/movie_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

  <header class="header-2">
    <div class="page-header min-vh-75 relative" style="background-image: url('{% static 'img/back.jpeg' %}')">
    <span class="mask bg-gradient-primary opacity-4"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-7 d-flex justify-content-center flex-column">
              <h1 class="text-white mb-4">{{ movie.title}}</h1>
              <p class="text-white opacity-8 lead pe-5 me-5">You can find here all movie  </p>
              <div class="buttons">
                <a href="{% url "movie:update-movie" pk=movie.id%}" type="button" class="btn btn-white mt-4">Update Movie</a>
              </div>
              <div class="buttons">
                <a href="{% url "movie:delete-movie" pk=movie.id%}" type="button" class="btn btn-white mt-4">Delete Movie</a>
              </div>
            </div>
        </div>
      </div>
    </div>
  </header>


  <div class="card card-body blur shadow-blur mx-3 mx-md-7 mt-n6">
  <!-- -------- START Features w/ icons and text on left & gradient title and text on right -------- -->
    <section class="pt-6 pb-2">
      <div class="container card card-frame">
        <div class="row card-body mx-md-auto">
          <div class="col-lg-4">
            <img class="img-fluid rounded" src="{{ movie.poster.url}}" alt="">
          </div>
          <div class="col-lg-8">
            <p class=""><strong>Title: </strong>{{ movie.title}}</p>
            <p><strong>Tagline: </strong>{{ movie.tagline}}</p>
            {% for director in movie.directors.all %}
              <p><strong>Directors: </strong>
                {{ director.first_name}} {{director.last_name }}
              </p>
            {% endfor %}
            <p><strong>Country: </strong>{{ movie.country}}</p>
            <p><strong>Budget: </strong>{{ movie.budget}}$</p>
            <p><strong>Fess in world: </strong>{{ movie.fess_in_world}}$</p>
            <p><strong>World Premier: </strong>{{ movie.world_premiere}}</p>
            <p><strong>Year: </strong>{{ movie.year}}</p>
            {% for genre in movie.genres.all %}
              <p><strong>Genre: </strong>{{ genre.name}}</p>
            {% endfor %}
            <p><strong>Description: </strong>{{ movie.description }}</p>
          </div>
        </div>

        </div>

    </section>



    <section class="py-5">

        <div class="container card card-frame">
        <h3 class="text-center z-index-1 position-relative">Actors</h3>
        <div class="row card-body">
          <div class="owl-carousel owl-theme mx-auto">
            {% for actor in movie.actors.all %}
              <div class="item text-center">
                <article class="avatar avatar-xxl rounded-circle">
                  <img alt="Image placeholder" src="{{ actor.avatar.url }}">
                </article>
                <p>{{ actor.first_name }} {{ actor.last_name }}</p>

              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </section>
    <form action="{% url 'movie:add-review' pk=movie.id%}" method="post">
      <div class="row">
        <div class="col-lg-10 mx-auto">
          <h5 class="text-center">Write review about this film</h5>
          {% csrf_token %}
           <div class="input-group input-group-dynamic mb-4">
              <span class="input-group-text" id="basic-addon1"></span>
              <input type="text" name="text" class="form-control" placeholder="Write here your review about film..." aria-label="Write here your review" aria-describedby="basic-addon1">
              <input type="hidden" name="movie" value="{{ movie.id }}">
              {% if user.is_authenticated %}
                <input type="hidden" name="user" value="{{ user.id }}">
              {% endif %}
         </div>
         <input class="btn btn-primary  mx-sm-auto" type="submit" value="Submit">
        </div>
      </div>
    </form>
  </div>

  <div class="card card-frame mx-3 mx-md-7 mt-3 p-3">
      <h5 class="text-center">Reviews</h5>
      {% if movie.reviews_set.count > 0 %}
        {% for review in movie.reviews_set.all %}
          <h6>@{{ review.user.username }}</h6>
          <p>{{ review.text }}</p>
        {% endfor %}
      {% else %}
        <p>There are no reviews yet!</p>
      {% endif %}
    </div>
<!-- -------- END Features w/ icons and text on left & gradient title and text on right -------- -->



{% endblock %}

templates/movie/movie_list.html
{% extends "base.html" %}
{% load query_transform %}
{% load static %}

{% block content %}
  <!-- Header -->
  <!-- -------- START HEADER 1 w/ text and image on right ------- -->
  <header>
    <div class="page-header min-vh-100" style="background-image: url({% static 'img/back.jpeg'%});" loading="lazy">
      <span class="mask bg-gradient-dark opacity-5"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-7 d-flex justify-content-center flex-column">
            <h1 class="text-white mb-4">Movie Library</h1>
            <p class="text-white opacity-8 lead pe-5 me-5">You can find here all movie  </p>
            <div class="buttons">
              <a href="#content" type="button" class="btn btn-white mt-4">Get Started</a>
            </div>
            <div class="buttons">
              <a href="{% url "movie:create-movie" %}" type="button" class="btn btn-white mt-4">Create Movie</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
<!-- -------- END HEADER 1 w/ text and image on right ------- -->
  <!--End Header -->



  <div id="content" class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
    <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 mx-auto py-3">
          <div class="row">
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state1">{{ movie.count }}</span>+</h1>
                <h5 class="mt-3">Number Movie</h5>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"> <span id="state2">{{ get_actors.count }}</span>+</h1>
                <h5 class="mt-3">Number Actors</h5>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary" id="state3"><span id="state3">{{ get_genres.count }}</span>+</h1>
                <h5 class="mt-3">Number Genres</h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
      <section class="py-3">
        <div class="container">
          <div class="row">
            <h4 class="mb-5 text-center">Filters</h4>
            <div class="col-lg-6">
            </div>
          </div>
        <!-- block -->
            <div class="row">
              {% include "include/filter_form.html" %}
              {% include "include/search_form.html" %}
            </div>
            <div class="row">
            <h4 class="text-center mb-4">Movies</h4>
            </div>
            <div class="row">
               {% for movie in movie_list %}
                  <div class="card-group col-lg-3 col-md-6 my-3">
                    <div class="card" data-animation="true">
                      <div class="card-header p-0 position-relative mt-n4 z-index-2">
                        <a href="{% url 'movie:movie-detail' pk=movie.id %}" class="d-block blur-shadow-image">
                          <img src="{{movie.poster.url}}" alt="img-blur-shadow" class="img-fluid shadow border-radius-lg">
                        </a>
                      </div>
                      <div class="card-body text-center">
                        <div class="d-flex mt-n6">
                          <p class="mx-auto">Click to read info</p>
                        </div>
                        <h5 class="font-weight-normal mt-3">
                          <a href="{% url 'movie:movie-detail' pk=movie.id %}">{{ movie.title }}</a>
                        </h5>
                      </div>
                      <hr class="dark horizontal my-0">
                      <div class="card-footer d-flex">
                        <p class="font-weight-normal my-auto">{{movie.year}}</p>
                        <i class="material-icons position-relative ms-auto text-lg me-1 my-auto">place</i>
                        <p class="text-sm my-auto"> {{ movie.country}}</p>
                      </div>
                    </div>
                  </div>
              {% endfor %}
            </div>


          </div>

      </section>

    </div>
      {% block pagination %}
        {% include 'include/pagination.html' %}
      {% endblock %}
  </div>
{% endblock %}

templates/movie/movie_update.html
{%  extends "base.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block content %}

  <header class="header-2">
    <div class="page-header min-vh-75 relative" style="background-image: url('{% static 'img/back.jpeg' %}')">
    <span class="mask bg-gradient-primary opacity-4"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-7 d-flex justify-content-center flex-column">
              <h1 class="text-white mb-4">{{ movie.title}}</h1>
              <p class="text-white opacity-8 lead pe-5 me-5">Update Movie</p>
              <div class="buttons">
                <a href="#content" pk=movie.id%}" type="button" class="btn btn-white mt-4">Get Started</a>
              </div>
            </div>
        </div>
      </div>
    </div>
  </header>

  <section>
  <div class="card card-body blur shadow-blur mx-3 mx-md-7 mt-n6">
  <!-- -------- START Features w/ icons and text on left & gradient title and text on right -------- -->
    <section class="pt-6 pb-2">
      <div class="container card card-frame">
        <div class="row">
          <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
            <h3 class="text-center">Update Movie</h3>
            <form role="form" id="movie-form" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% if form.non_field_errors %}
                  {% for error in form.non_field_errors %}
                      <div class="alert alert-danger" role="alert">
                          {{ error }}
                      </div>
                  {% endfor %}
              {% endif %}

              <div class="form-group">
                  <label for="id_title">Title</label>
                  <input type="text" class="form-control border" id="id_title" name="title" value="{{ movie.title }}">
              </div>

              <div class="form-group">
                  <label for="id_tagline">Tagline</label>
                  <input type="text" class="form-control border" id="id_tagline" name="tagline" value="{{ movie.tagline }}">
              </div>

              <div class="form-group">
                  <label for="id_description">Description</label>
                  <textarea class="form-control border" id="id_description" name="description" rows="4">{{ movie.description }}</textarea>
              </div>

              <div class="form-group mt-3">
                  <label for="id_poster">Poster</label>
                  <input type="file" class="form-control-file border" id="id_poster" name="poster" accept="image/*" required>
              </div>

              <div class="form-group">
                  <label for="id_year">Release Year</label>
                  <input type="number" class="form-control border" id="id_year" name="year" value="{{ movie.year }}">
              </div>

              <div class="form-group">
                  <label for="id_country">Country</label>
                  <input type="text" class="form-control border" id="id_country" name="country" value="{{ movie.country }}">
              </div>

              <div class="form-group">
                  <label for="id_genres">Genres</label>
                  <select multiple class="form-control border" id="id_genres" name="genres">
                      {% for genre in get_genres %}
                          <option value="{{ genre.id }}" {% if genre in movie.genres.all %} selected {% endif %}>{{ genre }}</option>
                      {% endfor %}
                  </select>
              </div>

              <div class="form-group">
                  <label for="id_actors">Actors</label>
                  <select multiple class="form-control border" id="id_actors" name="actors">
                      {% for actor in get_actors %}
                          <option value="{{ actor.id }}" {% if actor in movie.actors.all %} selected {% endif %}>{{ actor }}</option>
                      {% endfor %}
                  </select>
              </div>

              <div class="form-group">
                  <label for="id_directors">Directors</label>
                  <select multiple class="form-control border" id="id_directors" name="directors">
                      {% for director in get_actors %}
                          <option value="{{ director.id }}" {% if director in movie.directors.all %} selected {% endif %}>{{ director }}</option>
                      {% endfor %}
                  </select>
              </div>

              <div class="form-group">
                  <label for="id_fess_in_world">Fees in World</label>
                  <input type="number" class="form-control border" id="id_fess_in_world" name="fess_in_world" value="{{ movie.fess_in_world }}">
              </div>

              <div class="form-group">
                  <label for="id_budget">Budget</label>
                  <input type="number" class="form-control border" id="id_budget" name="budget" value="{{ movie.budget }}">
              </div>

              <div class="form-group">
                  <label for="id_world_premiere">World Premiere</label>
                  <input type="date" class="form-control border" id="id_world_premiere" name="world_premiere" value="{{ movie.world_premiere|date:'Y-m-d'  }}">
              </div>

              <div class="row">
                <div class="col-md-12 mt-3">
                  <button type="submit" class="btn bg-gradient-dark w-100">Update Movie</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
  </div>
</section>


{% endblock %}